language: python
python: 2.7

sudo: required

# dependencies
install:
  # pyside
  - sudo apt-get install -y qt4-qmake libqt4-dev
  - sudo apt-get install -y python-qt4 python-pyside

#pip install pyside --find-links wheelhouse/
#pip install PySide --no-index --find-links https://parkin.github.io/python-wheelhouse/;

# run tests
script:
  - pytest tests
